### ISSUE TITLE
Extend maximum emojis per message to 100

### ISSUE THREAD

**Issue by nastys** [DrKLO/Telegram#961] opened 2015-03-30 13:49 UTC
Hello, my friends and I noticed that if you send more than 50 emojis in the same message, the default set is used instead of the Apple Color Emoji set.
My phones (Android 4.4.4 and 5.0.2) show the emojis from the Noto font (screenshot 1 and 2, both from my 5.0.2 phone), while the phone of one of my friends, which has Android 4.1.2 (if I recall correctly), shows the emojis from the standard font (screenshot 3).

OK, I know it's a duplicate of #900 and that this happens because of performance issues but 50 just isn't enough. Please extend the limit to at least 70 or 80, if not 100 emojis.

![Screenshot 1](https://cloud.githubusercontent.com/assets/7950891/6897332/49306660-d6f3-11e4-9896-9772429f5b77.png)
![Screenshot 2](https://cloud.githubusercontent.com/assets/7950891/6897338/534d020c-d6f3-11e4-9580-fe69189f9cb9.png)
![Screenshot 3](https://cloud.githubusercontent.com/assets/7950891/6897343/5acdfa9a-d6f3-11e4-9b2e-b75c03f823be.jpg)

**Comment by 3mph4515** [comment] 2015-03-30 14:06
@nastys, Duplicate of duplicate. 
#900 
Use search

**Comment by nastys** [comment] 2015-03-30 14:10
@3mph4515 Sorry, I missed it...
Anyway, could this limit be extended to 100 emojis? Because 50 isn't enough.
My friend keeps saying things like "Why does this not happen in WhatsApp?" etc..

**Comment by wp9015362** [comment] 2015-03-30 15:20
> @nastys wrote:
> 
> Sorry, I missed it...

Here are the other threads with some more comments:

https://github.com/DrKLO/Telegram/issues/374
https://github.com/DrKLO/Telegram/issues/720

**Comment by nastys** [comment] 2015-03-30 16:35
@wp9015362 I really didn't notice issues #900 and #720 
Issue #374 is about extending to 200 emojis, this issue is about extending to 100.
It's easy to use more than 50 emojis, but it is unlikely to use more than 100.

**Comment by eckcon** [comment] 2015-03-30 19:58
lets hope nobody starts issues about extending to 120, 150 or 162 emojis ;-)

**Comment by nastys** [comment] 2015-03-30 20:12
@eckcon It's highly unlikely, but maybe in a couple of years... :)
100 emojis don't slow down Telegram too much anyway. If not 100 at least 70 or 80 please...

**Closed** 2015-03-31 13:32 UTC
